### ISSUE TITLE
Log after install: could not read addon description of ...

### ISSUE THREAD

**Issue by mz83** [stereodruid/OSMOSIS#3]
Thanks for giving this script a new lease on life!

Removing the script.module.pydevd dependency lines (quick Google search didn't return anything newer than 3.4.1) solves one problem, but after doing that, the install process still fails halfway through with the following log entries:

> 13:35:47 T:8112   ERROR: CAddonInstallJob[plugin.video.osmosis]: could not read addon description of special://home/addons/plugin.video.osmosis
13:36:00 T:3664  NOTICE: service.libraryautoupdate-0.9.8 : Skipping scan, only run when idle

Environment is Krypton Beta 2 on a Windows 10 x64 machine.

**Comment by stereodruid** [comment]
Thanks for the info. I will check this.

Am 08.10.2016 13:45 schrieb "Michael Zock" <notifications@github.com>:

**Comment by stereodruid** [comment]
I fixed the addons description.
What is the name of your addon folder, in ".....kodi\addons"?
Ws it "plugins.video.osmosis" or plugin.video.osmosis-master"?

Plz test the new version i added in this mail.

Sorry for my bad english. I am not a native speaker.

Regards

2016-10-08 14:04 GMT+02:00 Jan Gina <stereodruid@gmail.com>:

**Comment by mz83** [comment]
Don't worry, my native language is German, but it's better to keep this project in English because in the end the purpose of this software goes beyond just fixing the German xStream addon.

Seems like we're making progress. 
Now an attempt to install it results in an on-screen message about a missing dependency and nothing relevant in the log file beyond the following entries:

> 16:56:49 T:12960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: object of type 'NoneType' has no len()
                                            Traceback (most recent call last):
                                              File "C:\Users\HP\AppData\Roaming\Kodi\addons\plugin.video.osmosis\service.py", line 73, in <module>
                                                strm_update()
                                              File "C:\Users\HP\AppData\Roaming\Kodi\addons\plugin.video.osmosis\service.py", line 66, in strm_update
                                                for i in range(len(thelist)):
                                            TypeError: object of type 'NoneType' has no len()
                                            -->End of Python script error report<--
16:56:51 T:12956   ERROR: Previous line repeats 1 times.
16:56:51 T:12956  NOTICE: VideoInfoScanner: Starting scan ..

I'm a web developer (Java sector), so I know how frustrating this can be, but the error message changing from before still counts as a change.

**Comment by stereodruid** [comment]
KO, so this problem is already described in issue 2(Fehler bei installation). 
It was a mistake of mine. The auto update program treys to update content, logged in settings2.xml.
But as long as you haven't added any movies or series it cant work. so the function returns error.
I already have a solution, just need to be implemented.

**Comment by stereodruid** [comment]
Please read the solution and following text in issue (Fehler bei installation)

**Comment by stereodruid** [comment]
As the first Problem is solved i will close this issue.
